#!/bin/bash
set -eux

ROOT="$(dirname "$(readlink -f "$0")")"
MODULES_DIR="${ROOT}"/deployment_scripts/puppet/modules
RPM_REPO="${ROOT}"/repositories/centos/
DEB_REPO="${ROOT}"/repositories/ubuntu/

cat <<EOF | sudo tee /etc/yum.repos.d/grafana.repo
[grafana]
name=grafana
baseurl=https://packagecloud.io/grafana/stable/el/6/\$basearch
repo_gpgcheck=1
enabled=1
gpgcheck=1
gpgkey=https://packagecloud.io/gpg.key https://grafanarel.s3.amazonaws.com/RPM-GPG-KEY-grafana
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt
EOF



function download_packages {
    while [ $# -gt 0 ]; do
        FILENAME=$(basename "$1")
        EXT=${FILENAME##*.}
        case ${EXT} in
            deb) REPO=$DEB_REPO;;
            rpm) REPO=$RPM_REPO;;
        esac

        rm -f "$REPO"/"$FILENAME"
        wget -qO - "$1" > "$REPO"/"$FILENAME"
        shift
    done
}


echo "creating influxdb and grafana repositories"
cat <<EOF | sudo tee /etc/yum.repos.d/influxdb.repo
[influxdb]
name = InfluxDB Repository - RHEL \$releasever
baseurl = https://repos.influxdata.com/rhel/\$releasever/\$basearch/stable
enabled = 1
gpgcheck = 0 
gpgkey = https://repos.influxdata.com/influxdb.key
EOF


cat <<EOF | sudo tee /etc/yum.repos.d/grafana.repo
[grafana]
name=grafana
baseurl=https://packagecloud.io/grafana/stable/el/6/\$basearch
repo_gpgcheck=1
enabled=1
gpgcheck=1
gpgkey=https://packagecloud.io/gpg.key https://grafanarel.s3.amazonaws.com/RPM-GPG-KEY-grafana
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt
EOF

echo "Installing all required packages"
yum install -y influxdb
yum install -y grafana
systemctl start grafana
systemctl start influxdb
