#!/bin/bash
set -eux

. "$(dirname "$(readlink -f "$0")")"/functions.sh

# Puppet manifests
CONCAT_TARBALL_URL="https://forgeapi.puppetlabs.com/v3/files/puppetlabs-concat-1.2.4.tar.gz"
STDLIB_TARBALL_URL="https://forgeapi.puppetlabs.com/v3/files/puppetlabs-stdlib-4.7.0.tar.gz"
ELASTICSEARCH_TARBALL_URL="https://forgeapi.puppetlabs.com/v3/files/elasticsearch-elasticsearch-0.10.1.tar.gz"
# Dependency for Elasticsearch 0.10.x
DATACAT_TARBALL_URL="https://forgeapi.puppetlabs.com/v3/files/richardc-datacat-0.6.2.tar.gz"
FIREWALL_TARBALL_URL="https://forgeapi.puppetlabs.com/v3/files/puppetlabs-firewall-1.7.2.tar.gz"
APACHE_TARBALL_URL="https://forgeapi.puppetlabs.com/v3/files/puppetlabs-apache-1.4.0.tar.gz"
HTPASSWD_TARBALL_URL="https://forgeapi.puppetlabs.com/v3/files/leinaddm-htpasswd-0.0.3.tar.gz"

TZ_VERSION="2016j-0ubuntu0.14.04_all"

# Install puppet manifests
download_puppet_module "concat" "$CONCAT_TARBALL_URL"
download_puppet_module "stdlib" "$STDLIB_TARBALL_URL"
download_puppet_module "elasticsearch" "$ELASTICSEARCH_TARBALL_URL"
download_puppet_module "firewall" "$FIREWALL_TARBALL_URL"
download_puppet_module "datacat" "$DATACAT_TARBALL_URL"
download_puppet_module "apache" "${APACHE_TARBALL_URL}"
download_puppet_module "htpasswd" "${HTPASSWD_TARBALL_URL}"

# Update tzdata-java package to remove strict dependency on tzdata (see LP bug #1560436)
ROOT="$(dirname "$(readlink -f "$0")")"
DEB_REPO="${ROOT}"/repositories/ubuntu/
TMP_DIR=$(mktemp -d || exit 1)
cp "${DEB_REPO}/tzdata-java_${TZ_VERSION}.deb" "${TMP_DIR}"
cd "${TMP_DIR}" || exit 1
ar x "tzdata-java_${TZ_VERSION}.deb" || exit 1
tar xzvf control.tar.gz || exit 1
sed -i 's/Depends: tzdata (=/Depends: tzdata (>=/' control || exit 1
tar czvf control.tar.gz md5sums control || exit 1
ar r "tzdata-java_${TZ_VERSION}.deb" control.tar.gz data.tar.xz || exit 1
mv "tzdata-java_${TZ_VERSION}.deb" "${DEB_REPO}/" || exit 1
cd /tmp || exit 1
rm -rf "${TMP_DIR}" || exit 1
